### ISSUE TITLE
Need licenses

### ISSUE THREAD

**Issue by bmaranville** [h5wasm/h5wasm-plugins#1]
We need an appropriate license for this repo, as well as maybe a way to include licenses for re-distributing the libraries that are being built by this project?

@Ingvord if you could help with this, it would be greatly appreciated.

**Comment by Ingvord** [comment]
Totally! Will try my best. Here are some questions right out from the top of my mind:

Do you want to allow commercial use?
Do you want to force to open source projects that uses this one?
I am not sure what do you mean when saying "re-distributing" the libraries? You want to deliver the artifact of `npm install`?

Thanks

**Comment by bmaranville** [comment]
I'm not opposed to commercial use, though this software was initially created to support open science and open-source projects.  I would prefer to use a very open-source friendly license.

And yes, I am expecting to re-distribute these libraries through npm, in binary form (as .so files).  The licenses for the various libraries seemed to indicate that binary forms of the libraries should be accompanied by said licenses.

The authors of https://github.com/HDFGroup/hdf5_plugins (which gets pulled in as a source during the build of the plugins here) go to the effort of including the licenses in their source tree, for library sources they've copied.

**Comment by Ingvord** [comment]
AFAIK using `npm install` or basically creating any bundle in NodeJs world will contain licenses under `node_modules` folder. Unless otherwise specifically done to not to - we need just to build and check what is inside the resulting artifact.

So I would go with Apache 2. I will create the corresponding PR. Thanks
